/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-surface": "#1E293B",
        "tertiary-fixed": "#62fae3",
        "inverse-on-surface": "#233143",
        "on-primary-fixed": "#131b2e",
        "error-container": "#93000a",
        "primary-container": "#0f172a",
        "on-secondary-fixed": "#111c2d",
        "on-secondary": "#263143",
        "on-secondary-fixed-variant": "#3c475a",
        "secondary": "#bcc7de",
        "secondary-fixed-dim": "#bcc7de",
        "outline-variant": "#45464d",
        "surface-variant": "#273647",
        "on-tertiary-fixed": "#00201c",
        "primary-fixed": "#dae2fd",
        "surface-container-high": "#1c2b3c",
        "surface-container": "#122131",
        "outline": "#909097",
        "on-secondary-container": "#aeb9d0",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#ccfbf1",
        "on-error": "#690005",
        "on-primary-container": "#798098",
        "surface-container-low": "#0d1c2d",
        "error": "#fb923c",
        "surface-bright": "#2c3a4c",
        "surface-container-highest": "#273647",
        "surface-dim": "#051424",
        "background": "#F8FAFC",
        "primary-fixed-dim": "#bec6e0",
        "on-surface-variant": "#475569",
        "on-tertiary-container": "#009182",
        "surface-tint": "#bec6e0",
        "secondary-fixed": "#d8e3fb",
        "secondary-container": "#3e495d",
        "on-primary": "#283044",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#0D9488",
        "tertiary-fixed-dim": "#3cddc7",
        "inverse-primary": "#565e74",
        "on-primary-fixed-variant": "#3f465c",
        "on-tertiary-fixed-variant": "#005047",
        "surface": "#ffffff",
        "primary": "#3b82f6",
        "inverse-surface": "#1e293b",
        "on-tertiary": "#003731",
        "on-background": "#1e293b"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "gutter": "1.5rem",
        "stack-md": "1rem",
        "stack-lg": "2rem",
        "unit": "8px",
        "stack-sm": "0.5rem",
        "container-padding-desktop": "3rem",
        "container-padding-mobile": "1.5rem"
      },
      "fontFamily": {
        "display-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-md": ["JetBrains Mono"],
        "label-sm": ["JetBrains Mono"]
      },
      "fontSize": {
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
